// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cyOWPORPdMzo9-tZ3yI09Iu_exRof4U',
    appId: '1:461150287540:web:e363d1dd44b9d92ea2c9e1',
    messagingSenderId: '461150287540',
    projectId: 'aps-bms',
    authDomain: 'aps-bms.firebaseapp.com',
    storageBucket: 'aps-bms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDmUooUjP_KiRRNoa9-2i-qKJrzLK1Q0',
    appId: '1:461150287540:android:603236ea5c74a719a2c9e1',
    messagingSenderId: '461150287540',
    projectId: 'aps-bms',
    storageBucket: 'aps-bms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuA7D3YwIefUruQihTNJ1EYlFlyCizTYM',
    appId: '1:461150287540:ios:86279755a81740e7a2c9e1',
    messagingSenderId: '461150287540',
    projectId: 'aps-bms',
    storageBucket: 'aps-bms.firebasestorage.app',
    iosBundleId: 'com.example.bmsPointScheduleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuA7D3YwIefUruQihTNJ1EYlFlyCizTYM',
    appId: '1:461150287540:ios:86279755a81740e7a2c9e1',
    messagingSenderId: '461150287540',
    projectId: 'aps-bms',
    storageBucket: 'aps-bms.firebasestorage.app',
    iosBundleId: 'com.example.bmsPointScheduleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-cyOWPORPdMzo9-tZ3yI09Iu_exRof4U',
    appId: '1:461150287540:web:dd36b49930d3dde3a2c9e1',
    messagingSenderId: '461150287540',
    projectId: 'aps-bms',
    authDomain: 'aps-bms.firebaseapp.com',
    storageBucket: 'aps-bms.firebasestorage.app',
  );
}
